### ISSUE TITLE
2.49.0.77435 failing with numerous errors

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/HeroesDataParser#67]
Probably to be expected, but lots of warnings I won't post and this fatal:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at HeroesData.FileWriter.Writers.SprayData.SprayDataXmlWriter.MainElement(Spray spray)
   at HeroesData.FileWriter.Writers.WriterBase`2.<CreateOutputSingleFiles>b__53_1(T item)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at HeroesData.FileWriter.Writers.WriterBase`2.CreateOutputSingleFiles(IEnumerable`1 items)
   at HeroesData.FileWriter.Writers.WriterBase`2.CreateOutput(IEnumerable`1 items)
   at HeroesData.FileWriter.FileOutput.Create[T](IEnumerable`1 items, FileOutputType fileOutputType)
   at CallSite.Target(Closure , CallSite , FileOutput , Object , FileOutputType )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at HeroesData.App.<>c__DisplayClass105_0.<WriteFileOutput>b__0(DataProcessor parser)
   at HeroesData.App.DataProcessor(Action`1 action)
   at HeroesData.App.WriteFileOutput(FileOutputOptions options)
   at HeroesData.App.Run()
```

**Comment by koliva8245** [comment]
Fixed the error and I also checked out all the warnings. There should be 2 hero, 4 unit, 5 heroskin, and 1 spray warning.

This won't be released until next week.

Also there is a new raw description error I added for the next release, which thanks to blizzard we can see it in action from one of the hero warnings
```
[Deathwing] [DeathwingAspectOfDeath|DeathwingAspectOfDeath|Trait|True] FullTooltip contains an error tag
```
In the raw description you will see an `##ERROR##` tag which means the value before it (0 in this case) did not parse correctly. When parsed in the other descriptions, it will just be a 0.

**Comment by MGatner** [comment]
The develop artifact worked like a charm for the extract, but now it is failing on localization:
```
~/Library/HeroesDataParser/heroesdata localized-json ./gamestrings/                     
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at HeroesData.Commands.LocalizedTextToJsonCommand.ConvertFile(String filePath)
   at HeroesData.Commands.LocalizedTextToJsonCommand.<>c__DisplayClass3_0.<SetCommand>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at HeroesData.Program.Main(String[] args)
```

The game strings are definitely all there:
```
➜  HDP ls -l
total 392
-rw-r--r--   1 user  staff  152703 Nov 26 09:05 debug.log
drwxr-xr-x  14 user  staff     448 Nov 26 09:04 gamestrings
drwxr-xr-x  10 user  staff     320 Nov 26 09:05 images
drwxr-xr-x  15 user  staff     480 Nov 26 09:04 json
drwxr-xr-x  15 user  staff     480 Nov 26 09:04 xml
➜  HDP ls -l gamestrings 
total 75496
-rw-r--r--  1 user  staff  3081030 Nov 26 09:00 gamestrings_dede.txt
-rw-r--r--  1 user  staff  2776413 Nov 26 08:59 gamestrings_enus.txt
-rw-r--r--  1 user  staff  2996413 Nov 26 09:00 gamestrings_eses.txt
-rw-r--r--  1 user  staff  3010591 Nov 26 09:01 gamestrings_esmx.txt
-rw-r--r--  1 user  staff  3173257 Nov 26 09:01 gamestrings_frfr.txt
-rw-r--r--  1 user  staff  2925152 Nov 26 09:01 gamestrings_itit.txt
-rw-r--r--  1 user  staff  3108058 Nov 26 09:02 gamestrings_kokr.txt
-rw-r--r--  1 user  staff  3097606 Nov 26 09:02 gamestrings_plpl.txt
-rw-r--r--  1 user  staff  2907809 Nov 26 09:03 gamestrings_ptbr.txt
-rw-r--r--  1 user  staff  3952278 Nov 26 09:03 gamestrings_ruru.txt
-rw-r--r--  1 user  staff  2778059 Nov 26 09:04 gamestrings_zhcn.txt
-rw-r--r--  1 user  staff  2835951 Nov 26 09:04 gamestrings_zhtw.txt
```

**Comment by koliva8245** [comment]
Fixed. The command never work with gamestring files without version numbers.
