### ISSUE TITLE
PTR 2.50.0.79033 error: Too Many Requests

### ISSUE THREAD

**Issue by stuaroo** [HeroesToolChest/HeroesDataParser#72]
HDP v4.5.3, dotnet global tool, Heroes of the Storm PTR v2.50.0.79033, running `dotnet heroes-data "F:\Heroes PTR\Heroes of the Storm Public Test" --description 3 -e herodata -i heroportraits --output-directory out/ --warnings --localization all --json`

[enus.stormdata] finishes successfully but the next localization fails with the following: 

    [dede.stormdata]
    System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
       at System.Net.HttpWebRequest.GetResponse()
       at CASCLib.CDNIndexHandler.OpenDataFile(IndexEntry entry) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CDNIndexHandler.cs:line 170
       at CASCLib.CASCHandlerBase.OpenFileOnlineInternal(IndexEntry idxInfo, MD5Hash key) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandlerBase.cs:line 87
       at CASCLib.CASCHandler.OpenFileOnline(MD5Hash key) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandler.cs:line 239
       at CASCLib.CASCHandlerBase.OpenFile(MD5Hash key) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandlerBase.cs:line 78
       at CASCLib.CASCHandler.OpenFile(UInt64 hash) in D:\a\1\s\CASCExplorer\CascLib\CascLib\CASCHandler.cs:line 193
       at HeroesData.Loader.XmlGameData.CASCGameData.LoadHeroesDataStormMod() in D:\a\1\s\HeroesData.Loader\XmlGameData\CASCGameData.cs:line 165
       at HeroesData.Loader.XmlGameData.GameData.LoadFiles() in D:\a\1\s\HeroesData.Loader\XmlGameData\GameData.cs:line 815
       at HeroesData.Loader.XmlGameData.GameData.Load() in D:\a\1\s\HeroesData.Loader\XmlGameData\GameData.cs:line 793
       at HeroesData.Loader.XmlGameData.GameData.LoadGamestringFiles() in D:\a\1\s\HeroesData.Loader\XmlGameData\GameData.cs:line 325
       at HeroesData.App.LoadGameStrings(Localization localization) in D:\a\1\s\HeroesData\App.cs:line 597
       at HeroesData.App.Run() in D:\a\1\s\HeroesData\App.cs:line 146

**Comment by MGatner** [comment]
@stuaroo IIRC this error can be fixed by launching the PTR and going into Try Mode (or any game) so it the client downloads additional assets.

**Comment by koliva8245** [comment]
Yeah, just start up Heroes of the Storm, don't need to actually start a game.

**Comment by stuaroo** [comment]
Hmm, I did start up the PTR but did not attempt to join any games or go into Try Mode.  I'll give that a go.

**Comment by koliva8245** [comment]
Yeah so its not getting the data. The data is usually downloaded from when you start up Heroes of Storm. So you may have to re-install ptr.

**Comment by stuaroo** [comment]
Ok, sounds like this is user error on my part, I'll go ahead and close this then.  Thank you both for the help!

**Comment by koliva8245** [comment]
Alright, an FYI, you don't have to reinstall the game. Just go to your launcher, go to the games settings for the Heroes of the Storm (or for ptr) and change the text language to a language. Then Update the game. Then keep changing the text langauage/update to all the languages you want.
