### ISSUE TITLE
Unhandled exception. System.IO.IOException

### ISSUE THREAD

**Issue by Theofane** [HeroesToolChest/HeroesDataParser#73]
$ dotnet-heroes-data -e -all
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Heroes Data Parser (4.7.0)
  --https://github.com/HeroesToolChest/HeroesDataParser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 'Heroes of the Storm' directory
Localization(s): enus

Loading local CASC storage...please wait
Unhandled exception. System.IO.IOException: Descripteur non valide
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at HeroesData.CASCHotsStorage.DrawProgressBar(Single percent, Int32 barSize, Char progressCharacter) in D:\a\1\s\HeroesData\CASCHotsStorage.cs:line 32
   at HeroesData.CASCHotsStorage.<>c__DisplayClass13_0.<Initialize>b__2(Object _, RunWorkerCompletedEventArgs e) in D:\a\1\s\HeroesData\CASCHotsStorage.cs:line 105
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by koliva8245** [comment]
It's `-e all` (without the hyphen on all). If that somehow doesn't solve the problem then what operating system are you on and what are you using for the terminal?
